<?php

/**
 * Model_Albums
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Model_Albums extends Model_Base_Albums
{
    public function addAlbum($artist, $title, $novel ,$multiCheckbox, $selectlang, $multiselect , $image=NULL) {
        if($image != '') {
           $this->artist = $artist;
           $this->title = $title;
           $this->novel = $novel;
           $this->multiCheckbox = $multiCheckbox;
           $this->selectlang = $selectlang;
           $this->multiselect = $multiselect;
           $this->image = $image;
            $this->save();
       } else
       {
           $this->artist = $artist;
           $this->title = $title;
           $this->novel = $novel;
           $this->multiCheckbox = $multiCheckbox;
           $this->selectlang = $selectlang;
           $this->multiselect = $multiselect;
           $this->save();
       }
    }



    public function updateAlbum($id, $artist, $title , $novel, $multiCheckbox, $selectlang, $multiselect, $image) {  
        $form = new Application_Form_Album();
        $con = Doctrine_Manager::getInstance()->connection();
        $res = $con->execute("UPDATE albums SET artist = '".$data['artist']."',title =  '".$data['title']."'  ,novel =  '".$data['novel']."',multiCheckbox =  '".$data['multiCheckbox']."',selectlang =  '".$data['selectlang']."',multiselect =  '".$data['multiselect']."',image =  '".$data['image']."' WHERE id=".$data['id'], array(1));
        $this->_helper->redirector('index');
    }

    public function getAlbum($id) {
        $id = (int)$id;
        $con = Doctrine_Manager::getInstance()->connection();
        $res = $con->execute("SELECT * FROM albums where id=$id;", array(1));
        $retorno = $res->fetchAll();
        $retorno = $retorno['0'];
        if (!$retorno) {
            throw new Exception("Could not find row $id");
        }
        return $retorno;
    }

    public function deleteAlbum($id) {
        $con = Doctrine_Manager::getInstance()->connection();
        $row = $con->execute("DELETE FROM albums WHERE id =$id;", array(1));
        return $row;
    }
}
