<?php

/**
 * Model_Authentication
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
use Zend\View\Helper;

class Model_Authentication extends Model_Base_Authentication
{
    public function checkAuthentication($email, $password) {
        $con = Doctrine_Manager::getInstance()->connection();
        $res = $con->execute("select email from authentication where email='".$email."' and password='".$password."';", array(1));
        $retorno = $res->fetchAll();
        if(empty($retorno)) {
            return false;
        }
        return true;
    }
}