<?php

/**
 * Model_AuthenticationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_AuthenticationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_AuthenticationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_Authentication');
    }
}